spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

api:
  translateUrl: https://api-free.deepl.com/v2/translate
  apiKey: "ZjcwYWJhYTktNmE4NS1kMzg3LWQxYTEtNDQxYTQyY2FmYTM0OmZ4"